# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWidgets import QLabel
from PyQt5.QtWidgets import QWidget
from PyQt5 import QtWidgets
from PyQt5 import QtCore
from PyQt5 import QtGui
from PyQt5 import *
from PyQt5.QtGui import *
import sys

app = QApplication(sys.argv)
window = QWidget()

def close():
        sys.exit(0)

window.setObjectName("window")
window.setEnabled(True)
window.resize(400, 300)
window.setStyleSheet("background-color: rgb(31, 31, 31);")
window.setWindowFlags(QtCore.Qt.FramelessWindowHint)
LBL_NetworkSecurity = QtWidgets.QLabel(window)
LBL_NetworkSecurity.setGeometry(QtCore.QRect(30, 0, 141, 41))
LBL_NetworkSecurity.setLayoutDirection(QtCore.Qt.LeftToRight)
LBL_NetworkSecurity.setStyleSheet("color: #fff;\n"
                                  "font-size: 12px;")
LBL_NetworkSecurity.setObjectName("LBL_NetworkSecurity")
LBL_EnterNetworkCredentials = QtWidgets.QLabel(window)
LBL_EnterNetworkCredentials.setGeometry(QtCore.QRect(30, 20, 321, 51))
LBL_EnterNetworkCredentials.setStyleSheet("color: #fff;\n"
                                          "font-size: 19px;\n"
                                          "background:none;")
LBL_EnterNetworkCredentials.setObjectName("LBL_EnterNetworkCredentials")
LBL_EnterYourCredentialsToConnectTo = QtWidgets.QLabel(window)
LBL_EnterYourCredentialsToConnectTo.setGeometry(
    QtCore.QRect(30, 65, 261, 16))
LBL_EnterYourCredentialsToConnectTo.setStyleSheet("color: #fff;\n"
                                                  "background:none;\n"
                                                  "font-size: 12px;")
LBL_EnterYourCredentialsToConnectTo.setObjectName(
    "LBL_EnterYourCredentialsToConnectTo")
lineEdit = QtWidgets.QLineEdit(window)
lineEdit.setGeometry(QtCore.QRect(30, 95, 261, 31))
lineEdit.setStyleSheet("color: #fff;\n"
                       "font-family: open-sans;\n"
                       "font-size:12px;\n"
                       "background: rgba(31, 31, 31, 0);\n"
                       "height: 30px;\n"
                       "padding-left: 10px;")
lineEdit.setObjectName("lineEdit")
lineEdit_2 = QtWidgets.QLineEdit(window)
lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
lineEdit_2.setGeometry(QtCore.QRect(30, 135, 261, 31))
lineEdit_2.setStyleSheet("color: #fff;\n"
                         "font-family: open-sans;\n"
                         "font-size:12px;\n"
                         "background: rgba(31, 31, 31, 0);\n"
                         "height: 30px;\n"
                         "padding-left: 10px;")
lineEdit_2.setObjectName("lineEdit_2")
CHBX_Remember = QtWidgets.QCheckBox(window)
CHBX_Remember.setGeometry(QtCore.QRect(30, 200, 231, 21))
CHBX_Remember.setStyleSheet("color: #fff;\n"
                            "font-size: 12px;\n"
                            "background:none;\n"
                            "")
CHBX_Remember.setTristate(False)
CHBX_Remember.setObjectName("CHBX_Remember")
BTN_OK = QtWidgets.QPushButton(window)
BTN_OK.setGeometry(QtCore.QRect(30, 240, 171, 31))
BTN_OK.setStyleSheet("QPushButton { color: #fff;\n"
                     "border:none;background-color: #4C4C4C;}"
                     "QPushButton:pressed { color: #fff;\n"
                     "border: 1px solid #fff; }")

BTN_OK.setObjectName("BTN_OK")

BTN_Cancel = QtWidgets.QPushButton(window)
BTN_Cancel.setGeometry(QtCore.QRect(210, 240, 161, 31))
BTN_Cancel.setStyleSheet("QPushButton { color: #fff;\n"
                         "border:none;background-color: #4C4C4C;}"
                         "QPushButton:pressed { color: #fff;\n"
                         "border: 1px solid #fff; }")
BTN_Cancel.setObjectName("BTN_Cancel")
BTN_Cancel.clicked.connect(close)
BTN_X = QtWidgets.QPushButton(window)
BTN_X.setGeometry(QtCore.QRect(360, 10, 21, 23))
BTN_X.setStyleSheet("color: #fff;\n"
                    "border:none;")
BTN_X.setObjectName("BTN_X")
BTN_X.clicked.connect(close)
ADDRESS = QtWidgets.QLabel(window)
ADDRESS.setGeometry(QtCore.QRect(240, 65, 201, 16))
ADDRESS.setStyleSheet("color: #fff;\n"
                      "font-size:12px;")
ADDRESS.setObjectName("ADDRESS")
LBL_Domain = QtWidgets.QLabel(window)
LBL_Domain.setGeometry(QtCore.QRect(30, 175, 231, 21))
LBL_Domain.setStyleSheet("color: #fff;\n"
                      "font-size:12px;")
LBL_Domain.setObjectName("LBL_Domain")

DOMAIN = QtWidgets.QLabel(window)
DOMAIN.setGeometry(QtCore.QRect(100, 175, 231, 21))
DOMAIN.setStyleSheet("color: #fff;\n"
                      "font-size:12px;")
DOMAIN.setObjectName("LBL_Domain")

QtCore.QMetaObject.connectSlotsByName(window)
_translate = QtCore.QCoreApplication.translate
window.setWindowTitle(_translate("Frame", "Frame"))
LBL_NetworkSecurity.setText(_translate("Frame", "Network Security"))
LBL_EnterNetworkCredentials.setText(
    _translate("Frame", "Enter network credentials"))
LBL_EnterYourCredentialsToConnectTo.setText(_translate(
    "Frame", "Enter your credentials to connect to: "))
lineEdit.setPlaceholderText(_translate("Frame", "User name"))
lineEdit_2.setPlaceholderText(_translate("Frame", "Password"))
CHBX_Remember.setText(_translate("Frame", "Remember my credentials"))
BTN_OK.setText(_translate("Frame", "OK"))
BTN_Cancel.setText(_translate("Frame", "Cancel"))
BTN_X.setText(_translate("Frame", "X"))
ADDRESS.setText(_translate("Frame", "localhost"))
LBL_Domain.setText(_translate("Frame", "Connect to: "))
DOMAIN.setText(_translate("Frame", "WORKGROUP"))

window.show()
sys.exit(app.exec_())
